import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { PT_Serif } from "next/font/google";
import "./globals.css";

const lato = Lato({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-lato",
  display: "swap",
});

const ptSerif = PT_Serif({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-ptSerif",
  display: "swap",
});

/* const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.variable} ${ptSerif.variable}`}>
      <body>{children}</body>
    </html>
  );
}
